<a href="https://colab.research.google.com/github/supitcha0887/Python_LAB5/blob/main/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา : 66015xxx ชื่อ :

In [21]:
print("รหัสนักศึกษา : 67015188 ชื่อ: นส.สุพิชชา อิ่มทองใบ")

รหัสนักศึกษา : 67015188 ชื่อ: นส.สุพิชชา อิ่มทองใบ


Exercise 5.1 ให้เขียน function ชื่อ day_of_year(day, month ,year) โดยมีการคืนค่า คือ day_of_years เป็นวันที่ลำดับที่เท่าใดของปีคริสตศักราช year
ปีที่เป็น Leap Year เดือนกุมภาพันธ์จะมี 29 วัน
ให้สร้างฟังก์ชัน is_leap เพื่อตรวจสอบ leap year แยกออกมา และให้ฟังก์ชัน day_of_year เรียกใช้ is_leap อีกที


In [ ]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
def is_leap(year):
  if year % 4 ==0:
    if year %100 == 0:
      if year %400 == 0:
        return True
      else:
        return False
    else:
      return True
  else:
    return False
def day_of_year(day, month, year):
  if is_leap(year):
    days_in_month[1] = 29
  else:
    days_in_month[1] = 28
  day_of_year = sum(days_in_month[:month-1])+day
  return day_of_year
# Testcases
print("Normal year (2023):")
print(f"1 Jan 2023: {day_of_year(1, 1, 2023)}")  # ควรได้ 1
print(f"1 Feb 2023: {day_of_year(1, 2, 2023)}")  # ควรได้ 32
print(f"1 Mar 2023: {day_of_year(1, 3, 2023)}")  # ควรได้ 60
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

print("\nLeap year (2024):")
print(f"1 Jan 2024: {day_of_year(1, 1, 2024)}")  # ควรได้ 1
print(f"29 Feb 2024: {day_of_year(29, 2, 2024)}")  # ควรได้ 60
print(f"1 Mar 2024: {day_of_year(1, 3, 2024)}")  # ควรได้ 61
print(f"31 Dec 2024: {day_of_year(31, 12, 2024)}")  # ควรได้ 366

print("\nCentury year, not a leap year (1900):")
print(f"1 Mar 1900: {day_of_year(1, 3, 1900)}")  # ควรได้ 60

print("\nCentury year, leap year (2000):")
print(f"1 Mar 2000: {day_of_year(1, 3, 2000)}")  # ควรได้ 61

print("\nMid-year dates:")
print(f"15 Jun 2023: {day_of_year(15, 6, 2023)}")  # ควรได้ 166
print(f"15 Jun 2024: {day_of_year(15, 6, 2024)}")  # ควรได้ 167 (Leap year)

print("\nLast day of each quarter:")
print(f"31 Mar 2023: {day_of_year(31, 3, 2023)}")  # ควรได้ 90
print(f"30 Jun 2023: {day_of_year(30, 6, 2023)}")  # ควรได้ 18
print(f"30 Sep 2023: {day_of_year(30, 9, 2023)}")  # ควรได้ 273
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

Normal year (2023):
1 Jan 2023: 1
1 Feb 2023: 32
1 Mar 2023: 60
31 Dec 2023: 365

Leap year (2024):
1 Jan 2024: 1
29 Feb 2024: 60
1 Mar 2024: 61
31 Dec 2024: 366

Century year, not a leap year (1900):
1 Mar 1900: 60

Century year, leap year (2000):
1 Mar 2000: 61

Mid-year dates:
15 Jun 2023: 166
15 Jun 2024: 167

Last day of each quarter:
31 Mar 2023: 90
30 Jun 2023: 181
30 Sep 2023: 273
31 Dec 2023: 365


Exercise 5.2 ให้เขียนฟังก์ชัน เพิ่มเติมเป็น date_diff
รับข้อมูลในรูปแบบ “dd-mm-yyyy” เช่น date_diff(“1-1-2018”, “1-1-2020”) จะได้ 731 วัน date_diff(“25-12-1999”, “9-3-2000”) จะได้ 76 วัน
ให้เขียนฟังก์ชัน day_in_year โดยจะส่งค่าจำนวนวันของปี (365 หรือ 366) โดยรับข้อมูลเป็น ปี
ส่งคืนข้อมูลเป็นจำนวนวันตั้งแต่วันที่แรก จนถึงวันที่สอง โดยรวมทั้ง 2 วันนั้นเข้าไปด้วย
ให้สมมติว่าวันแรก จะต้องมาก่อนวันที่สองเสมอ ดังนั้นไม่ต้องตรวจสอบ


In [ ]:
def is_leap(year):
    if year % 4 == 0:
        if year % 100 == 0:
            if year % 400 == 0:
                return True
            else:
                return False
        else:
            return True
    else:
        return False


def day_in_year(year):
    if is_leap(year):
        return 366
    else:
        return 365


def day_of_year(day, month, year):
    days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    if is_leap(year):
        days_in_month[1] = 29

    day_of_year = sum(days_in_month[:month - 1]) + day
    return day_of_year


def date_diff(date1, date2):
    splited_date1 = date1.split("-")
    year1 = int(splited_date1[2])
    month1 = int(splited_date1[1])
    day1 = int(splited_date1[0])

    splited_date2 = date2.split("-")
    year2 = int(splited_date2[2])
    month2 = int(splited_date2[1])
    day2 = int(splited_date2[0])

    years = []
    for year in range(year1 + 1, year2):
        years.append(year)

    total_date_by_year = []
    for year in years:
        total_date_by_year.append(
            day_in_year(year)
        )

    if year2 - year1 > 0:
        rank_of_endyear1 = day_of_year(day=31, month=12, year=year1)
        rank_of_date1 = day_of_year(day=day1, month=month1, year=year1)
        total_date_by_year.append(rank_of_endyear1 - rank_of_date1 + 1)
        rank_of_date2 = day_of_year(day=day2, month=month2, year=year2)
        total_date_by_year.append(rank_of_date2)
    else:
        rank_of_date1 = day_of_year(day=day1, month=month1, year=year1)
        rank_of_date2 = day_of_year(day=day2, month=month2, year=year2)
        total_date_by_year.append(rank_of_date2 - rank_of_date1 + 1)
    print(f"{date1} to {date2}: {sum(total_date_by_year)}")


date_diff("25-12-1999", "9-3-2000")  # ควรได้ 76
date_diff("1-1-2000", "1-1-2001")  # ควรได้ 367 (ปี 2000 เป็น leap year)
date_diff("1-1-2001", "1-1-2002")  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
date_diff("1-3-2000", "1-3-2001")  # ควรได้ 367 (ข้ามปี leap year)
date_diff("1-1-2023", "31-12-2023")  # ควรได้ 365 (ทั้งปี 2023)

25-12-1999 to 9-3-2000: 76
1-1-2000 to 1-1-2001: 367
1-1-2001 to 1-1-2002: 366
1-3-2000 to 1-3-2001: 366
1-1-2023 to 31-12-2023: 365


Exercise 5.3 จากโปรแกรม 5.2 ให้เขียนฟังก์ชัน date_diff  เพิ่มเติม โดยให้มีการตรวจสอบ
วันที่ต้องเป็นวันที่ถูกต้องของเดือนนั้นๆ
เดือนต้องอยู่ระหว่าง 1-12
เดือนกุมภาพันธ์ของปีที่มี Leap Year เท่านั้นที่จะมี 29 วันได้
หากข้อมูล Input ผิดพลาด ให้ Return -1


In [ ]:
def is_leap(year):
    if year % 4 == 0:
        if year % 100 == 0:
            if year % 400 == 0:
                return True
            else:
                return False
        else:
            return True
    else:
        return False

def day_in_year(year):
    if is_leap(year):
        return 366
    else:
        return 365

def days_in_month(month, year):
    days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    if is_leap(year):
        days[1] = 29
    return days[month - 1]

def day_of_year(day, month, year):
    if month < 1 or month > 12:
        return -1
    if day < 1 or day > days_in_month(month, year):
        return -1
    day_of_year = sum(days_in_month(m, year) for m in range(1, month)) + day
    return day_of_year

def date_diff(date1, date2):
    splited_date1 = date1.split("-")
    splited_date2 = date2.split("-")

    if len(splited_date1) != 3 or len(splited_date2) != 3:
        return -1

    day1, month1, year1 = map(int, splited_date1)
    day2, month2, year2 = map(int, splited_date2)

    if day_of_year(day1, month1, year1) == -1 or day_of_year(day2, month2, year2) == -1:
        return -1

    if (year1 > year2) or (year1 == year2 and day_of_year(day1, month1, year1) > day_of_year(day2, month2, year2)):
        date1, date2 = date2, date1
        day1, month1, year1 = day2, month2, year2
        day2, month2, year2 = map(int, splited_date1)

    years = list(range(year1 + 1, year2))
    total_date_by_year = [day_in_year(year) for year in years]

    if year2 - year1 > 0:
        rank_of_endyear1 = day_of_year(31, 12, year1)
        rank_of_date1 = day_of_year(day1, month1, year1)
        total_date_by_year.append(rank_of_endyear1 - rank_of_date1 + 1)
        rank_of_date2 = day_of_year(day2, month2, year2)
        total_date_by_year.append(rank_of_date2)
    else:
        rank_of_date1 = day_of_year(day1, month1, year1)
        rank_of_date2 = day_of_year(day2, month2, year2)
        total_date_by_year.append(rank_of_date2 - rank_of_date1 + 1)
    return sum(total_date_by_year)
    #print(f"{date1} to {date2}: {sum(total_date_by_year)}")
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

# ทดสอบกรณีข้อมูลไม่ถูกต้อง
print(date_diff("31-4-2023", "1-5-2023"))  # ควรได้ -1 (เดือนเมษายนมี 30 วัน)
print(date_diff("29-2-2023", "1-3-2023"))  # ควรได้ -1 (ปี 2023 ไม่ใช่ leap year)
print(date_diff("1-13-2023", "1-1-2024"))  # ควรได้ -1 (เดือนไม่ถูกต้อง)
print(date_diff("abc", "1-1-2024"))  # ควรได้ -1 (รูปแบบวันที่ไม่ถูกต้อง)

731
76
367
366
366
365
-1
-1
-1
-1


1.	ปลาหมอคางดำเพศเมีย 1 ตัว เมื่ออายุครบ 2 เดือน จะสามารถสืบพันธ์ได้ โดยระยะเวลาตั้งท้องจนถึง
วางไข่ของตัวเมียจะใช้เวลา 21 วัน และฟักในปากเพศผู้อีก 7 วัน (สามารถรวมเป็น 1 เดือนได้) โดยออกไข่ครั้งละ 300 ฟอง กำหนดให้ไข่ฟักเป็นเพศผู้และเพศเมียอย่างละครึ่ง และเมื่อวางไข่แล้วจะสามารถสืบพันธ์ต่อได้ทันที กำหนดให้ปลามีอายุ 5 ปี และปลาทั้งหมดจะตาย p% ทุก 1 เดือน จงหาว่าปลาหมอคางดำหลุดจากฟาร์ม n ตัวเป็นเพศผู้และเพศเมียอย่างละครึ่ง จงเขียนโปรแกรมรับค่า n และ p ให้แสดงผลจำนวนปลาทุก 3 เดือน เป็นเวลา 10 ปี ให้เขียนเป็นฟังก์ชัน ชื่อ simulate_fish_population()


In [ ]:
def decreas_p_percent(fish_no,p):
    return fish_no - (fish_no * p) / 100

def get_egg(reproducable_fish):
    return (reproducable_fish // 2) * 300

def simulate_fish_population(n,p,months=3):
    states = []
    expired_states = []
    for month in range(1, 121):
        state = {
            "month": month,
            "egg": 0,
            "child_fish": 0,
            "new_fish": 0,
            "total_fish": 0,
            "reproducable_fish": 0
        }

        expired_state = {
            "month": month,
            "dead_fish": 0.0
        }

        if month == 1:
            state["egg"] = get_egg(reproducable_fish=n)
            state["child_fish"] = 0
            state["new_fish"] = 0
            state["reproducable_fish"] = n
            state["total_fish"] = n
            states.append(state)
            expired_state["dead_fish"] = n
            expired_states.append(expired_state)
        elif month == 2:
            prev_state = states[-1]
            state["egg"] = get_egg(reproducable_fish=prev_state["reproducable_fish"])
            state["child_fish"] = decreas_p_percent(prev_state["egg"], p=p)
            state["new_fish"] = 0
            state["total_fish"] = prev_state["total_fish"] + state["child_fish"] + state["new_fish"]
            state["reproducable_fish"] = prev_state["reproducable_fish"] + state["new_fish"]
            states.append(state)
            decrease1 = decreas_p_percent(fish_no=prev_state["egg"], p=p)
            decrease2 = decreas_p_percent(fish_no=decrease1, p=p)
            expired_state["dead_fish"] = decrease2
            expired_states.append(expired_state)
        else:
            if month < 60:
                prev_state = states[-1]
                state["egg"] = get_egg(reproducable_fish=prev_state["reproducable_fish"])
                state["child_fish"] = decreas_p_percent(prev_state["egg"], p=p)
                state["new_fish"] = decreas_p_percent(prev_state["child_fish"], p=p)
                state["reproducable_fish"] = prev_state["reproducable_fish"] + state["new_fish"]
                state["total_fish"] = state["reproducable_fish"] + state["child_fish"]
                states.append(state)

                expired_state["dead_fish"] = decreas_p_percent(fish_no=decreas_p_percent(fish_no=prev_state["egg"], p=p), p=p)
                expired_states.append(expired_state)
            else:
                prev_state = states[-1]
                dead_state = expired_states[month - 60]
                state["egg"] = get_egg(reproducable_fish=prev_state["reproducable_fish"])
                state["child_fish"] = decreas_p_percent(prev_state["egg"], p=p)
                state["new_fish"] = decreas_p_percent(prev_state["child_fish"], p=p)
                state["reproducable_fish"] = prev_state["reproducable_fish"] + state["new_fish"] - dead_state["dead_fish"]
                state["total_fish"] = state["reproducable_fish"] + state["child_fish"] - dead_state["dead_fish"]
                states.append(state)

                expired_state["dead_fish"] = decreas_p_percent(fish_no=decreas_p_percent(fish_no=prev_state["egg"], p=p), p=p)
                expired_states.append(expired_state)

        print(f"{state=}")
simulate_fish_population(n=n, p=p)

n = 2  # Initial number of fish
p = 10  # Monthly mortality rate

state={'month': 1, 'egg': 300, 'child_fish': 0, 'new_fish': 0, 'total_fish': 2, 'reproducable_fish': 2}
state={'month': 2, 'egg': 300, 'child_fish': 270.0, 'new_fish': 0, 'total_fish': 272.0, 'reproducable_fish': 2}
state={'month': 3, 'egg': 300, 'child_fish': 270.0, 'new_fish': 243.0, 'total_fish': 515.0, 'reproducable_fish': 245.0}
state={'month': 4, 'egg': 36600.0, 'child_fish': 270.0, 'new_fish': 243.0, 'total_fish': 758.0, 'reproducable_fish': 488.0}
state={'month': 5, 'egg': 73200.0, 'child_fish': 32940.0, 'new_fish': 243.0, 'total_fish': 33671.0, 'reproducable_fish': 731.0}
state={'month': 6, 'egg': 109500.0, 'child_fish': 65880.0, 'new_fish': 29646.0, 'total_fish': 96257.0, 'reproducable_fish': 30377.0}
state={'month': 7, 'egg': 4556400.0, 'child_fish': 98550.0, 'new_fish': 59292.0, 'total_fish': 188219.0, 'reproducable_fish': 89669.0}
state={'month': 8, 'egg': 13450200.0, 'child_fish': 4100760.0, 'new_fish': 88695.0, 'total_fish': 4279124.0, 'reproducable_fish': 178364.0}
stat

2.	ให้เขียน function find_mismatch ซึ่งรับ string มา 2 ค่า โดยจะส่งค่ากลับดังนี้
- 0 เมื่อ string ทั้ง 2 ตัว เหมือนกัน โดยไม่สนใจ case
- 1 เมื่อ string 1 จะเหมือน string 2 โดยการลบและ/หรือเพิ่มตัวอักษรเพียง 1 ตัว
- 2 เมื่อ string ไม่เข้าเกณฑ์ 0 หรือ 1


| String  1| 	String2	|ผลลัพธ์|
|----------|----------|------|
|Python|	Java	|2|
|book	 |  boot	|1|
|fan	 |  fun	  |1|
|sin	 | sink	  |1 เพราะเพิ่ม k ใน str2 แล้วจะเหมือนกัน
|Dog	 | dog	  |0
|poke	 | spoke	|1 เพิ่ม s ใน str2 แล้วเหมือนกัน
|poker |	poke	|1 ตัด r ใน str1 ออกแล้วเหมือนกัน






In [ ]:
def find_mismatch(str1, str2):
  if str1 == str2:
    return 0
  else:
        if len(str1) > len(str2):
          a = []
          for index in range(0,len(str1)):
            a.append(str1[:index] + str1[index + 1:])
          for word in a:
            if word == str2:
              return 1
          return 2
        elif len(str2) > len(str1):
            b = []
            for index in range(0,len(str2)):
              b.append(str2[:index] + str2[index + 1:])
            for word in b:
              if word == str1:
                return 1
            return 2
        elif len(str1) == len(str2):
          c = []
          d = []
          for index in range(0,len(str1)):
            c.append(str1[:index] + str1[index + 1:])
            d.append(str2[:index] + str2[index + 1:])
          for word in c:
            if word in d:
              return 1
          return 2

str1= input("").lower()
str2 = input("").lower()
check = find_mismatch(str1,str2)
print(check)





spoke
poke
1


3.	จากข้อ 1 ให้เขียนฟังก์ชันชื่อ spelling_correction โดยรับ 2 argument ตัวแรกเป็นประโยค (string) และตัวที่ 2 เป็น list ของคำ (correct_spells) โดยฟังก์ชันนี้มีหน้าที่ตรวจสอบแต่ละ word ใน input string กับคำที่อยู่ใน correct_spells โดยค่าที่คืนกลับมาจะมีดังนี้ (พยายามเรียกใช้ฟังก์ชันในข้อ 1)
-	ถ้าคำที่อยู่ในประโยค ตรงกับคำที่อยู่ใน correct_spells ทุกอย่าง ก็จะ copy ไปที่ output string
-	ถ้าคำที่อยู่ในประโยค ต่างจากคำที่อยู่ใน correct_spells โดยต่างกัน 1 ตัวอักษร โดยการเปลี่ยน การเพิ่ม หรือการลบ 1 ตัวอักษร คำที่อยู่ในประโยคจะถูกเปลี่ยนโดยคำที่อยู่ใน correct_spells และนำไปใส่ output string
-	ถ้าคำที่ไม่พบในเงื่อนไขข้างต้นให้นำคำนั้นไปใส่ output string ได้เลย
-	คำที่ประกอบด้วย 1 หรือ 2 ตัวอักษรจะไม่ตรวจสอบ ให้นำคำนั้นไปใส่ output string ได้เลย
-	ถ้ามี 2 คำใน correct_spells ที่ตรงตามเงื่อนไข ให้ใช้คำแรก
-	ไม่สนใจตัวใหญ่ ตัวเล็ก
-	Input string จะมีได้เพียงอักษรภาษาอังกฤษเท่านั้น
-	ในแต่ละคำจะคั่นด้วย 1 space ถ้ามี space มากกว่านั้นให้ตัดออก และตัด space จากหัวท้ายประโยค

|ประโยค	|correct_spells	|output string |
|-------|---------------|-------------|
|Thes is the Firs cas	|[‘that’,’first’,’case’,’car’]|	thes is the first car|
|programming is fan and easy	|[‘programming’,’this’,’fun’,’easy’,book’]	|programming is fun and easy|
|Thes is vary essy	|[‘this’,’is’,’very’,’easy’]	|this is very easy|
|Wee ipve Pythen	|[‘we’,’live’,’ln’,’Python’]	|we live python|




In [ ]:
def get_all_removed_char_words(word: str) -> list[str]:
    words: list[str] = []
    for index in range(0, len(word)):
        words.append(word[:index] + word[index + 1:])
    words.append(word)
    return words


def find_mismatch(str1: str, str2: str) -> int:
    lower_str1: str = str1.lower()
    lower_str2: str = str2.lower()
    if lower_str1 == lower_str2:
        return 0
    else:
        str1_words = get_all_removed_char_words(word=lower_str1)
        str2_words = get_all_removed_char_words(word=lower_str2)
        for word in str1_words:
            if word in str2_words:
                return 1
        return 2


def spelling_correction(input_string: str, correct_spells: list[str]) -> str:

    lower_input_string: str = input_string.lower()
    lower_input_words: list[str] = lower_input_string.split(" ")


    lower_correct_spells: list[str] = [word.lower() for word in correct_spells]

    output_string: str = ""
    for input_word in lower_input_words:
        if len(input_word) > 2:
            compare_time: int = 0
            for output_word in lower_correct_spells:
                is_matched: int = find_mismatch(str1=input_word, str2=output_word)
                compare_time += 1

                if is_matched == 0:
                    output_string += f"{input_word} "
                    break
                elif is_matched == 1:
                    output_string += f"{output_word} "
                    break

                if compare_time == len(lower_correct_spells):
                    output_string += f"{input_word} "

        else:
            output_string += f"{input_word} "

    return output_string


sentence: str = "Thes is the Firs cas"
correct_spells: list[str] = ["that", "first", "case", "car"]
spelled_sentence: str = spelling_correction(input_string=sentence, correct_spells=correct_spells)
print(spelled_sentence)

thes is the first case 


4. ให้เขียนฟังก์ชัน find_word_horizontal ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามแถวของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
	word='cat'
	find_word_horizontal(crosswords,word)
```

Output
   [2,1]


In [ ]:
def find_word_horizontal(crosswords, word):
    for row_index, row in enumerate(crosswords):
        row_str = ''.join(row)
        col_index = row_str.find(word)
        if col_index != -1:
            return (row_index, col_index)
    return None
crosswords = [
    ['s', 'd', 'o', 'g'],
    ['c', 'u', 'c', 'm'],
    ['a', 'c', 'a', 't'],
    ['t', 'e', 't', 'k']
]
word = 'cat'

result = find_word_horizontal(crosswords, word)
print(result)

(2, 1)


5. ให้เขียนฟังก์ชัน find_word_vertical ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามคอลัมน์ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

ตัวอย่าง
```
	crosswords=[['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t',' e','t','k']]
	word='cat'
	find_word_vertical(crosswords,word)
```

Output
   [1,0]


In [ ]:
def find_word_vertical(crosswords, word):
    num_rows = len(crosswords)
    num_cols = len(crosswords[0]) if num_rows > 0 else 0

    for col_index in range(num_cols):
        col_str = ''.join(crosswords[row_index][col_index] for row_index in range(num_rows))

        row_index = col_str.find(word)
        if row_index != -1:
            return (row_index, col_index)

    return None
crosswords = [
    ['s', 'd', 'o', 'g'],
    ['c', 'u', 'c', 'm'],
    ['a', 'c', 'a', 't'],
    ['t', 'e', 't', 'k']
]
word = 'cat'

result = find_word_vertical(crosswords, word)
print(result)

(1, 0)


6.	ให้เขียนฟังก์ชัน capitalize_word_in_crossword จะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตาม row และ column ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบจะเปลี่ยนเป็นตัวใหญ่และ และส่งคืน list ที่แก้ไขแล้ว แต่ถ้าไม่เจอจะส่ง list เดิมกลับมา ให้ใช้ฟังก์ชันตามข้อ 3 และ 4 ช่วย

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','x','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
```
จะส่งค่ากลับ
```
 [['s','d','o','g'],
  ['C','u','c','m'],
  ['A','x','a','t'],
  ['T','e','t','k']]
```
```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
จะส่งค่ากลับ                   
[['s','d','o','g'],
 ['c','u','c','m'],
 ['a','C','A','T'],
 ['t','e','t','k']]
```




In [20]:
def find_word_horizontal(crosswords, word):
    for row_index, row in enumerate(crosswords):
        row_str = ''.join(row)
        col_index = row_str.find(word)
        if col_index != -1:
            return (row_index, col_index)
    return None

def find_word_vertical(crosswords, word):
    num_rows = len(crosswords)
    num_cols = len(crosswords[0]) if num_rows > 0 else 0

    for col_index in range(num_cols):
        col_str = ''.join(crosswords[row_index][col_index] for row_index in range(num_rows))
        row_index = col_str.find(word)
        if row_index != -1:
            return (row_index, col_index)
    return None

def capitalize_word_in_crossword(crosswords, word):
    original_crosswords = [row[:] for row in crosswords]
    horizontal_position = find_word_horizontal(crosswords, word)
    if horizontal_position:
        row_index, col_index = horizontal_position
        for i in range(len(word)):
            crosswords[row_index][col_index + i] = crosswords[row_index][col_index + i].upper()

    vertical_position = find_word_vertical(crosswords, word)
    if vertical_position:
        row_index, col_index = vertical_position
        for i in range(len(word)):
            crosswords[row_index + i][col_index] = crosswords[row_index + i][col_index].upper()

    if crosswords == original_crosswords:
        return original_crosswords
    return crosswords

crosswords = [
    ['s', 'd', 'o', 'g'],
    ['c', 'u', 'c', 'm'],
    ['a', 'x', 'a', 't'],
    ['t', 'e', 't', 'k']
]
word = 'cat'

result = capitalize_word_in_crossword(crosswords, word)
for row in result:
    print(row)


['s', 'd', 'o', 'g']
['C', 'u', 'c', 'm']
['A', 'x', 'a', 't']
['T', 'e', 't', 'k']
